### ISSUE TITLE
About Installation

### ISSUE THREAD

**Issue by CoreLine76** [kristapsk/bitcoin-scripts#22]
Can you give some more details about your setup? I couldn't build it, master

**Comment by kristapsk** [comment]
There's nothing to build. Just start scripts from the same directory they are located.

I have installer for my [cln-scripts](https://github.com/kristapsk/cln-scripts) project, could think about something similar here one day.

**Comment by CoreLine76** [comment]
Sir, we should install bitcoind server before running these, is it true?

**Comment by kristapsk** [comment]
@CoreLine76 Yes, you need full node, and these use `bitcoin-cli`.

**Comment by CoreLine76** [comment]
I'm getting such an error and I don't know how to proceed.
[https://www.hizliresim.com/sciw8gh](url)

**Comment by kristapsk** [comment]
It looks you are running Ubuntu. Bitcoin-qt GUI does not contain `bitcoin-cli` there, you should install `bitcoind` package too IIRC (`apt-get install bitcoind`).

**Comment by CoreLine76** [comment]
dostum@ubuntu:~/bitcoin-scripts$ bitcoin-cli -testnet --host=127.00.1 --port=19839 --rpcuser=koregazisi -rpcpassword=XXXXX
/usr/lib/node_modules/bitcoin-cli/index.js:27
    throw new Error('Coudn\'t found bitcoin.conf file, use --rpcuser=USER and --rpcpassword=PASS');
    ^

Error: Coudn't found bitcoin.conf file, use --rpcuser=USER and --rpcpassword=PASS
    at Object.<anonymous> (/usr/lib/node_modules/bitcoin-cli/index.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/lib/node_modules/bitcoin-cli/bin/bitcoin-cli:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
dostum@ubuntu:~/bitcoin-scripts$

**Comment by CoreLine76** [comment]
> It looks you are running Ubuntu. Bitcoin-qt GUI does not contain `bitcoin-cli` there, you should install `bitcoind` package too IIRC (`apt-get install bitcoind`).

dostum@ubuntu:~$ sudo apt-get bitcoind
[sudo] password for dostum: 
E: Invalid operation bitcoind

**Comment by CoreLine76** [comment]
dostum@ubuntu:~$ sudo add-apt-repository ppa:bitcoin/bitcoin
Repository: 'deb https://ppa.launchpadcontent.net/bitcoin/bitcoin/ubuntu/ jammy main'
Description:
NOT MAINTAINED. The OS-library linking packages here had a series of issues.

PLEASE DOWNLOAD DIRECTLY FROM bitcoincore.org (and verify the signatures of said files).

IF YOU WANT AUTO-UPDATES, please see the officially-maintained snap package -
https://github.com/bitcoin-core/packaging/tree/master/snap
More info: https://launchpad.net/~bitcoin/+archive/ubuntu/bitcoin
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/bitcoin-ubuntu-bitcoin-jammy.list
Adding deb entry to /etc/apt/sources.list.d/bitcoin-ubuntu-bitcoin-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/bitcoin-ubuntu-bitcoin-jammy.list
Adding key to /etc/apt/trusted.gpg.d/bitcoin-ubuntu-bitcoin.gpg with fingerprint C70EF1F0305A1ADB9986DBD8D46F45428842CE5E
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease              
Hit:3 https://deb.nodesource.com/node_14.x impish InRelease                    
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Ign:5 https://ppa.launchpadcontent.net/bitcoin/bitcoin/ubuntu jammy InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Err:7 https://ppa.launchpadcontent.net/bitcoin/bitcoin/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done                              
E: The repository 'https://ppa.launchpadcontent.net/bitcoin/bitcoin/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
dostum@ubuntu:~$ sudo apt update
Hit:1 https://deb.nodesource.com/node_14.x impish InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy InRelease                      
Ign:4 https://ppa.launchpadcontent.net/bitcoin/bitcoin/ubuntu jammy InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease            
Err:7 https://ppa.launchpadcontent.net/bitcoin/bitcoin/ubuntu jammy Release    
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/bitcoin/bitcoin/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
dostum@ubuntu:~$ sudo apt install bitcoind
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package bitcoind
dostum@ubuntu:~$

**Comment by kristapsk** [comment]
[Bitcoin Stackexchange suggest](https://bitcoin.stackexchange.com/questions/10010/how-to-install-a-bitcoin-client-on-ubuntu-server) to try `sudo apt-get install bitcoin`. I don't run Ubuntu myself.

**Comment by CoreLine76** [comment]
> [Bitcoin Stackexchange suggest](https://bitcoin.stackexchange.com/questions/10010/how-to-install-a-bitcoin-client-on-ubuntu-server) `sudo apt-get install bitcoin`. I don't run Ubuntu myself.

Which operating system should I use?

**Comment by CoreLine76** [comment]
Thank you. please closed ticket.

**Comment by kristapsk** [comment]
@CoreLine76 You solved the issue for you?
